### ISSUE TITLE
粗糙模糊核估计推导过程

### ISSUE THREAD

**Issue by SunR54** [huacheng/Shift-Invariant-Deblurring#2]
你好，请问快速的粗糙模糊核估计那一步，最小化目标函数（两个二范数的和）的推导公式中，空间域到频域那一步有什么参考资料可以借鉴吗？

**Comment by huacheng** [comment]
这个就是日常的傅里叶变换过程，使用傅里叶变换主要是方便卷积的处理。
将空间域的卷积运算，变换成频域的矩阵简单对应元素相乘运算。
